### ISSUE TITLE
Able to install manylinux wheel but not auditwheel repair it

### ISSUE THREAD

**Issue by riddell-stan** [pypa/auditwheel#145]
I'm getting a strange error when I run `auditwheel` on a wheel I built in a manylinux docker image:

```
$ docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD auditwheel repair /io/wheelhouse/pystan-2.19.0.0-cp36-cp36m-linux_x86_64.whl -w /io/wheelhouse2/
warning [/io/wheelhouse/pystan-2.19.0.0-cp36-cp36m-linux_x86_64.whl]:  76 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [/io/wheelhouse/pystan-2.19.0.0-cp36-cp36m-linux_x86_64.whl]:  reported length of central directory is
  -76 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
  zipfile?).  Compensating...
error:  expected central file header signature not found (file #67320).
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
Repairing pystan-2.19.0.0-cp36-cp36m-linux_x86_64.whl
Traceback (most recent call last):
  File "/usr/local/bin/auditwheel", line 10, in <module>
    sys.exit(main())
  File "/opt/_internal/cpython-3.6.8/lib/python3.6/site-packages/auditwheel/main.py", line 49, in main
    rval = args.func(args, p)
  File "/opt/_internal/cpython-3.6.8/lib/python3.6/site-packages/auditwheel/main_repair.py", line 56, in execute
    wheel_abi = analyze_wheel_abi(args.WHEEL_FILE)
  File "/opt/_internal/cpython-3.6.8/lib/python3.6/site-packages/auditwheel/wheel_abi.py", line 101, in analyze_wheel_abi
    get_wheel_elfdata(wheel_fn)
  File "/opt/_internal/cpython-3.6.8/lib/python3.6/site-packages/auditwheel/wheel_abi.py", line 35, in get_wheel_elfdata
    with InGenericPkgCtx(wheel_fn) as ctx:
  File "/opt/_internal/cpython-3.6.8/lib/python3.6/site-packages/auditwheel/wheeltools.py", line 155, in __enter__
    self.path = super(InWheelCtx, self).__enter__()
  File "/opt/_internal/cpython-3.6.8/lib/python3.6/site-packages/auditwheel/wheeltools.py", line 114, in __enter__
    zip2dir(self.in_wheel, self.name)
  File "/opt/_internal/cpython-3.6.8/lib/python3.6/site-packages/auditwheel/tools.py", line 42, in zip2dir
    subprocess.check_output(['unzip', '-o', '-d', out_dir, zip_fname])
  File "/opt/_internal/cpython-3.6.8/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/opt/_internal/cpython-3.6.8/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['unzip', '-o', '-d', '/tmp/tmp5yrvpbxz', '/io/wheelhouse/pystan-2.19.0.0-cp36-cp36m-linux_x86_64.whl']' returned non-zero exit status 3.
```

I can unzip this file without issue and even install it (without error) on linux.

The wheel is large (196M). The wheel was built using TkTech's verison of ``quay.io/pypa/manylinux1_x86_64`` https://github.com/pypa/manylinux/issues/118#issuecomment-472380364 .

**Comment by riddell-stan** [comment]
I found the problem. The wheel contains 73,451 files and the `unzip` used by `manylinux1` (5.52) does not support the [Zip64](https://en.wikipedia.org/wiki/Zip_%28file_format%29#ZIP64) format, so it is limited to 65,535 (2^16) files.

So auditwheel breaks in this case.

Installing a newer version of `unzip` on the manylinux1 image solves this problem.

**Comment by ehashman** [comment]
Ah! I had a suspicion it was something like that...

Is the version of unzip on the manylinux2010 image new enough?

**Comment by riddell-stan** [comment]
Yes. unzip 6.00 with `zombiefeynman/manylinux2010_x86_64`.
