### ISSUE TITLE
issue with auditwheel repair

### ISSUE THREAD

**Issue by hroest** [pypa/auditwheel#279]
# Issue 

We have found that `auditwheel repair` processes some of our shared objects such that they are broken after processing. After processing a wheel built with 
```
 auditwheel repair "$whl" -w wheelhouse/
```

and installing the resulting wheel, the python package is broken:

```
/tmp/# $PYBIN/bin/python -c "import pyopenms"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/python/cp37-cp37m/lib/python3.7/site-packages/pyopenms/__init__.py", line 65, in <module>
    raise e
  File "/opt/python/cp37-cp37m/lib/python3.7/site-packages/pyopenms/__init__.py", line 35, in <module>
    from .all_modules import *
  File "/opt/python/cp37-cp37m/lib/python3.7/site-packages/pyopenms/all_modules.py", line 1, in <module>
    from .pyopenms_1 import *
ImportError: /opt/python/cp37-cp37m/lib/python3.7/site-packages/pyopenms/.libs/libQt5Core-82077f0c.so.5.9.4: undefined symbol: stderr, version 6
# echo $PYBIN
/opt/python/cp37-cp37m/
```

## Workaround

Our current workaround is to unpack the wheel and replace the `libQt5Core.so` library in the `.libs` folder manually with the system one in  "/qt/lib/libQt5Core.so.5.9.4" which works for now. Similarly, if you replace the above library with the one used during the build, it works:

```
# ls -tlrh /qt/lib/libQt5Core.so.5.9.4
-rwxr-xr-x 1 root root 5.9M Nov 27 18:00 /qt/lib/libQt5Core.so.5.9.4
# ls -tlrh /tmp/libQt5Core-82077f0c.so.5.9.4 
-rwxr-xr-x 1 root root 6.2M Nov 30 16:25 /tmp/libQt5Core-82077f0c.so.5.9.4
```

curiously, the library is actually larger after processing with auditwheel.

## Reproducing the issue

You can reproduce the issue using the following script https://github.com/OpenMS/OpenMS/blob/feature/py_release/src/pyOpenMS/dist-scripts/create-manylinux.sh - note that our build takes a while

# Debug information

## Image

We use the following image:

```
Digest: sha256:c4161c855cfe3f6e50c38a8e5a5eae839431542ea89fd00475a378ffcd8c9875
Status: Image is up to date for quay.io/pypa/manylinux1_x86_64:latest

# docker images | grep manylin | grep quay
quay.io/pypa/manylinux1_x86_64      latest              80957eca29a3        11 days ago         878MB
```

# Show

```
# auditwheel show wheelhouse_tmp/pyopenms-2.4.0-cp37-cp37m-linux_x86_64.whl

pyopenms-2.4.0-cp37-cp37m-linux_x86_64.whl is consistent with the
following platform tag: "linux_x86_64".

The wheel references external versioned symbols in these system-
provided shared libraries: libpthread.so.0 with versions
{'GLIBC_2.2.5'}, libgcc_s.so.1 with versions {'GCC_3.0'}, libm.so.6
with versions {'GLIBC_2.2.5'}, libQt5Core.so.5 with versions
{'Qt_5.9', 'Qt_5'}, libc.so.6 with versions {'GLIBC_2.2.5'},
libstdc++.so.6 with versions {'GLIBCXX_3.4.6', 'GLIBCXX_3.4',
'CXXABI_1.3', 'CXXABI_1.3.1'}

The following external shared libraries are required by the wheel:
{
    "libOpenMS.so": "/openms-build-cp37-cp37m/lib/libOpenMS.so",
    "libOpenSwathAlgo.so": "/openms-build-cp37-cp37m/lib/libOpenSwathAlgo.so",
    "libQt5Core.so.5": "/qt/lib/libQt5Core.so.5.9.4",
    "libQt5Network.so.5": "/qt/lib/libQt5Network.so.5.9.4",
    "libSuperHirn.so": "/openms-build-cp37-cp37m/lib/libSuperHirn.so",
    "libc.so.6": "/lib64/libc-2.5.so",
    "libdl.so.2": "/lib64/libdl-2.5.so",
    "libgcc_s.so.1": "/lib64/libgcc_s-4.1.2-20080825.so.1",
    "libglib-2.0.so.0": "/lib64/libglib-2.0.so.0.1200.3",
    "libgthread-2.0.so.0": "/lib64/libgthread-2.0.so.0.1200.3",
    "libm.so.6": "/lib64/libm-2.5.so",
    "libpthread.so.0": "/lib64/libpthread-2.5.so",
    "librt.so.1": "/lib64/librt-2.5.so",
    "libstdc++.so.6": "/usr/lib64/libstdc++.so.6.0.8",
    "libz.so.1": "/contrib-build/lib/libz.so.1.2.11"
}

In order to achieve the tag platform tag "manylinux1_x86_64" the
following shared library dependencies will need to be eliminated:

libOpenMS.so, libOpenSwathAlgo.so, libQt5Core.so.5,
libQt5Network.so.5, libSuperHirn.so, libz.so.1
```

**Comment by lkollar** [comment]
I wonder if this was due to a bug in `patchelf`. @hroest can you still reproduce this?
