### ISSUE TITLE
Unable to find shared object files when installing wheels repaired with auditwheel==5.2.0

### ISSUE THREAD

**Issue by adamgregory** [pypa/auditwheel#402]
Ubuntu focal, Python 3.8.10

Within one ubuntu:focal docker container install python3.8 and the necessary ubuntu packages to build and repair the wheel for mysqlclient python package (requires libmysqlclient-dev):
```
docker run --rm -it -v /tmp/wheels:/tmp/wheels ubuntu:focal bash
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:deadsnakes/ppa
apt-get update
apt-get install -y python3.8 python3-dev libpython3.8 build-essential virtualenv libmysqlclient-dev patchelf

virtualenv -p python3.8 pyenv
. pyenv/bin/activate
pip install --upgrade pip wheel auditwheel==5.2.0
pip wheel --wheel-dir /tmp/wheels mysqlclient~=2.1
auditwheel repair --plat linux_x86_64 --only-plat --wheel-dir=/tmp/wheels --no-update-tags /tmp/wheels/mysqlclient*.whl
```

In a second container attempt to install the wheel which was built and repaired in the first container:
```
docker run --rm -it -v /tmp/wheels:/tmp/wheels ubuntu:focal bash
apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:deadsnakes/ppa
apt-get update
apt-get install -y python3.8 libpython3.8 virtualenv

virtualenv -p python3.8 pyenv
. pyenv/bin/activate
pip install --upgrade pip
pip install --no-index --find-links=/tmp/wheels mysqlclient~=2.1
python
>>> import MySQLdb

Traceback (most recent call last):
  File "/pyenv/lib/python3.8/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: t-5eb3c521.so.21.2.31: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pyenv/lib/python3.8/site-packages/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined
```

The wheel installs fine, but when attempting to import modules which are included in the mysqlclient python package there is an error about missing shared object files.

When pinning to auditwheel<5.2.0 the wheel is repaired correctly and modules from the mysqlclient python package can be imported without errors.

**Comment by mayeut** [comment]
duplicates #401 

The version of patchelf on focal is buggy.
More info in #401
