### ISSUE TITLE
Error: no module named `wheel.pkginfo`

### ISSUE THREAD

**Issue by mrzv** [pypa/auditwheel#436]
When I run `auditwheel repair ...`, I get:
```
Traceback (most recent call last):
  File "/usr/bin/auditwheel", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/auditwheel/main.py", line 59, in main
    rval = args.func(args, p)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/auditwheel/main_repair.py", line 114, in execute
    from .repair import repair_wheel
  File "/usr/lib/python3.11/site-packages/auditwheel/repair.py", line 21, in <module>
    from .wheel_abi import get_wheel_elfdata
  File "/usr/lib/python3.11/site-packages/auditwheel/wheel_abi.py", line 20, in <module>
    from .genericpkgctx import InGenericPkgCtx
  File "/usr/lib/python3.11/site-packages/auditwheel/genericpkgctx.py", line 4, in <module>
    from .wheeltools import InWheelCtx
  File "/usr/lib/python3.11/site-packages/auditwheel/wheeltools.py", line 24, in <module>
    from wheel.pkginfo import read_pkg_info, write_pkg_info
ModuleNotFoundError: No module named 'wheel.pkginfo'
```

This is on ArchLinux, using Python 3.11.3, auditwheel 5.4.0, wheel 0.40.0.

**Comment by mayeut** [comment]
This is an issue with the ArchLinux package.
They un-vendored wheel from auditwheel which leads to this error.
Auditwheel does vendor wheel to prevent this kind of regression upon wheel updates as we are relying on private API (there are no public API) of the wheel package.
