### ISSUE TITLE
auditwheel does not work on musllinux_1_1_i686:

### ISSUE THREAD

**Issue by genotrance** [pypa/auditwheel#482]
Using v6.0.0 of auditwheel on quay.io/pypa/musllinux_1_1_i686:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/pyvenv/py3.11.8/lib/python3.11/site-packages/auditwheel/__main__.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/pyvenv/py3.11.8/lib/python3.11/site-packages/auditwheel/main.py", line 54, in main
    rval = args.func(args, p)
           ^^^^^^^^^^^^^^^^^^
  File "/root/pyvenv/py3.11.8/lib/python3.11/site-packages/auditwheel/main_repair.py", line 173, in execute
    out_wheel = repair_wheel(
                ^^^^^^^^^^^^^
  File "/root/pyvenv/py3.11.8/lib/python3.11/site-packages/auditwheel/repair.py", line 78, in repair_wheel
    raise ValueError(
ValueError: Cannot repair wheel, because required library "libc.musl-i386.so.1" could not be located
```
```
$ ls -l /lib
...
ld-musl-i386.so.1
libc.musl-x86.so.1 -> ld-musl-i386.so.1
```
So I created a symlink for libc.musl-i386.so.1:
```
libc.musl-i386.so.1 -> ld-musl-i386.so.1
```
Now when I run auditwheel, I get a different error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/pyvenv/py3.11.8/lib/python3.11/site-packages/auditwheel/__main__.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/pyvenv/py3.11.8/lib/python3.11/site-packages/auditwheel/main.py", line 39, in main
    main_repair.configure_parser(sub_parsers)
  File "/root/pyvenv/py3.11.8/lib/python3.11/site-packages/auditwheel/main_repair.py", line 43, in configure_parser
    p.add_argument(
  File "/opt/python/cp311-cp311/lib/python3.11/argparse.py", line 1450, in add_argument
    action = action_class(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/pyvenv/py3.11.8/lib/python3.11/site-packages/auditwheel/tools.py", line 122, in __init__
    raise argparse.ArgumentError(self, msg % args)
argparse.ArgumentError: argument --plat: invalid choice: 'musllinux_1_1_i686' from environment variable 'AUDITWHEEL_PLAT' (choose from 'linux_i686', 'manylinux_2_5_i686', 'manylinux_2_12_i686', 'manylinux_2_17_i686', 'manylinux_2_24_i686', 'manylinux_2_27_i686', 'manylinux_2_28_i686', 'manylinux_2_31_i686', 'manylinux_2_34_i686', 'manylinux_2_35_i686', 'manylinux1_i686', 'manylinux2010_i686', 'manylinux2014_i686')
```

**Comment by mayeut** [comment]
Will close given it's been one year.
Sorry for not getting back to you earlier but time spent on OpenSource is sparse.
The fact that I'm seeing `/root/pyvenv/py3.11.8` is weird. This does not come from `quay.io/pypa/musllinux_1_1_i686`. There might be some incompatibility in the way pyvenv builds things in the container or something else. Please use auditwheel preinstalled in the container, it was tested at least once a week at that time through manylinux / cibuildwheel projects.
Please note that musllinux_1_1 images are EOL.
