### ISSUE TITLE
fairseq is impossible to build on manylinux2014

### ISSUE THREAD

**Issue by rsxdalv** [pypa/auditwheel#499]
https://github.com/rsxdalv/fairseq/actions/runs/9848833912/job/27191510860#step:6:267
```
      + sh -c 'auditwheel repair -w /tmp/cibuildwheel/repaired_wheel /tmp/cibuildwheel/built_wheel/fairseq-0.12.4-cp310-cp310-linux_x86_64.whl'
  INFO:auditwheel.main_repair:Repairing fairseq-0.12.4-cp310-cp310-linux_x86_64.whl
  Traceback (most recent call last):
    File "/usr/local/bin/auditwheel", line 8, in <module>
      sys.exit(main())
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.10/site-packages/auditwheel/main.py", line 54, in main
      rval = args.func(args, p)
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.10/site-packages/auditwheel/main_repair.py", line 173, in execute
      out_wheel = repair_wheel(
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.10/site-packages/auditwheel/repair.py", line 78, in repair_wheel
      raise ValueError(
  ValueError: Cannot repair wheel, because required library "libtorch_cpu.so" could not be located
```

https://github.com/rsxdalv/fairseq/actions/runs/9848991100/job/27191954087#step:6:461
```
      + sh -c 'auditwheel repair -w /tmp/cibuildwheel/repaired_wheel /tmp/cibuildwheel/built_wheel/fairseq-0.12.5-cp310-cp310-linux_x86_64.whl'
  INFO:auditwheel.main_repair:Repairing fairseq-0.12.5-cp310-cp310-linux_x86_64.whl
  Traceback (most recent call last):
    File "/usr/local/bin/auditwheel", line 8, in <module>
      sys.exit(main())
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.10/site-packages/auditwheel/main.py", line 54, in main
      rval = args.func(args, p)
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.10/site-packages/auditwheel/main_repair.py", line 173, in execute
      out_wheel = repair_wheel(
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.10/site-packages/auditwheel/repair.py", line 78, in repair_wheel
      raise ValueError(
  ValueError: Cannot repair wheel, because required library "libtorch.so" could not be located
```

https://github.com/rsxdalv/fairseq/actions/runs/9882491448/job/27295454832#step:6:262
```
      + sh -c 'auditwheel repair -w /tmp/cibuildwheel/repaired_wheel /tmp/cibuildwheel/built_wheel/fairseq-0.12.12-cp310-cp310-linux_x86_64.whl'
  INFO:auditwheel.main_repair:Repairing fairseq-0.12.12-cp310-cp310-linux_x86_64.whl
  Traceback (most recent call last):
    File "/usr/local/bin/auditwheel", line 8, in <module>
      sys.exit(main())
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.10/site-packages/auditwheel/main.py", line 54, in main
      rval = args.func(args, p)
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.10/site-packages/auditwheel/main_repair.py", line 173, in execute
      out_wheel = repair_wheel(
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.10/site-packages/auditwheel/repair.py", line 78, in repair_wheel
      raise ValueError(
  ValueError: Cannot repair wheel, because required library "libtorch_python.so" could not be located
```

no matter what I specify in pyproject.toml I get a different failure.

```
[build-system]
requires = [
  "setuptools==69.5.1",
  "wheel",
  "cython",
  "numpy>=1.21.3",
# torch
]
build-backend = "setuptools.build_meta"
```

* if `torch==2.0.0`
  * I get libtorch_cpu.so could not be located
* if "torch @ https://download.pytorch.org/whl/cpu/torch-2.0.0%2Bcu118-cp310-cp310-linux_x86_64.whl"
  * I get libtorch.so could not be located
* if "torch @ https://download.pytorch.org/whl/cu118/torch-2.0.0%2Bcu118-cp310-cp310-linux_x86_64.whl",
  * I get libtorch_python.so could not be located

**Comment by mayeut** [comment]
reporter worked around the issue using `--exclude`
