### ISSUE TITLE
auditwhell missing import print_function in python2

### ISSUE THREAD

**Issue by austinzh** [pypa/auditwheel#64]
```
$pip show auditwheel
Name: auditwheel
Version: 1.5.0
Summary: Cross-distribution Linux wheels
Home-page: https://github.com/pypa/auditwheel
Author: Robert T. McGibbon
Author-email: rmcgibbo@gmail.com
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: setuptools, wheel, typing, pyelftools
```

```
 $auditwheel
Traceback (most recent call last):
  File "/usr/local/bin/auditwheel", line 6, in <module>
    from auditwheel.main import main
  File "/usr/local/lib/python2.7/dist-packages/auditwheel/main.py", line 8, in <module>
    from . import main_addtag
  File "/usr/local/lib/python2.7/dist-packages/auditwheel/main_addtag.py", line 3, in <module>
    from .policy import (load_policies, get_policy_name, get_priority_by_name,
  File "/usr/local/lib/python2.7/dist-packages/auditwheel/policy/__init__.py", line 26
    print('Error: This tool only supports Linux', file=sys.stderr)
                                                      ^
SyntaxError: invalid syntax
```
```
$uname -a
Linux A10092495U 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jamadden** [comment]
auditwheel [explicitly only supports Python 3.3+](https://github.com/pypa/auditwheel/blob/master/README.rst#installation). It does not run on Python 2.

**Comment by austinzh** [comment]
got it
